### ISSUE TITLE
Add one or more Next Steps

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#100]
**User story:**
As a TTA specialist creating an activity report, I want to enter the next steps that the grantee and I agreed on so we can assure that we have a clear agreement and hold each other accountable for continued progress.

**Acceptance criteria:**
- [ ] In a section of the Activity Report dedicated to next steps, the user can add 1 to _n_ next steps (required field)
- [ ] Next steps are added one at a time
- [ ] Next Steps are free text (no character limit)
- [ ] Users can edit/delete a next step
- [ ] Create separate table for next steps
 
**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880472
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880473/simulate/sitemap

**Exclusions:**

- post MVP areas for research and potential future development ([Jira 11](https://ocio-jira.acf.hhs.gov/browse/TTASH-11)): 
     - display of next steps elsewhere in the Hub besides the AR
     - sharing of the next steps with the grantee (since the grantee can be the assignee for a next step)
     - adding a "due date" selector

**Comment by pamlo412** [comment]
Discussion with Patrice: the grantee won't have direct access in the MVP, so is there a way we can make the next steps (or even the whole AR) available to the grantee. Not needed for MVP but it is the primary value of including next steps in an activity report.

**Comment by pamlo412** [comment]
> Discussion of user story with Patrice: the grantee won't have direct access in the MVP, so is there a way we can make the next steps (or even the whole AR) available to the grantee? Not needed for MVP but it is the primary value of including next steps in an activity report. We want to do usability testing to see what value the inclusion of next steps has for MVP users.

[Jira 11](https://ocio-jira.acf.hhs.gov/browse/TTASH-11) created for user research to explore this issue post MVP.
