### ISSUE TITLE
Create a new goal in an Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#101]
**User story:**
As a TTA specialist creating an activity report, I want to be able to create a new goal in my report so that I can document goals that may have emerged recently and not be recorded in the TTA Plan or elsewhere.

**Acceptance Criteria:**
- [ ] the user can create a new goal and enter it in an activity report 
- [ ] the goal has a "draft" indicator until the report has been approved @PatricePascual-ACF could we remove this requirement?
- [ ] New goals created in an activity report are available to all users creating reports for the same grantee/non-grantee once the report is approved.
- [ ] no character limit is imposed on this goal

**Exclusions:**
- selection of preexisting goals from TTA Plan Smartsheets #117 
- selection of preexisting goals from AR Smartsheets #214 
- display of entered goals #216 

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880470/simulate/sitemap

**Engineering notes**
- single input (free text) field
- save for goal happens when report is saved (autosave or intentional save)
- goal is associated with the grantee or non-grantee identified in the report who receive the TTA.

**Comment by PatricePascual-ACF** [comment]
User story: Review and Submit
As a TTA specialist creating an activity report, I want to review my work and:
Option 1: 
1. Send it to the collaborating specialist for them to add their contribution to the work. >>(They must be notified when I send to them)
2. Review the contributions from that other specialists >>(I must be notified when they have sent back to me.)

Option 2: 
Submit the report to my manager for review.

Option 3: 
Submit the report to my manager and my collaborating specialists' manager.

**Comment by pamlo412** [comment]
This story will be ready for grooming once @PatricePascual-ACF updates it with the preferred field labels.

**Comment by matt-dobson** [comment]
@PatricePascual-ACF referencing this design: https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/133952435/simulate/no-panels
This could maybe be broken down by capability - Goals, objectives, and narrative in separate stories.

**Comment by pamlo412** [comment]
Groomed this story with team. Assigned to @kryswisnaskas to review because she wasn't present. Story still needs to be pointed.
