### ISSUE TITLE
Add collaborators to draft Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#109]
**User story:**
As a specialist who is drafting an activity report, I want to select another collaborator from my region so they can review or edit the draft report.

**Acceptance Criteria:**
- [ ] author of a report that is still in draft can select one or more TTA Hub users from their region with whom they want to collaborate on the report
- [ ] TTA Hub users in the current user's region should be selectable 
- [ ] type-ahead is available to help narrow the list
- [ ] the selected user(s) are granted editing and submitting permissions for the draft report
- [ ] changes that collaborating users make in the report are not tracked (i.e. no version history or comments or ability to accept/reject)
- [ ] Post-MVP: Nice to have: the user has a way to find and select someone outside of their region (for Regions 11 and 12, espcially)

**Exclusions:**
- any sort of visual indicator (like a comment box) for collaborating specialists to note for each each other what changes they made or edits they recommend. This kind of indicator is only available in the manager's workflow for requesting revisions - see #138
- any sort of visual indicator allowing a collaborator to alert other collaborators when they're done they're part of the report work - the report will simply sit in the collaborators' queues on their Home page until one of them submits it and all listed managers approve it - see #
- any sort of tracking of changes/version/comments  
- submitting the report for approval, #135 
- actual push notifications - this work will be wanted in the future
- ability to see the report in the Home page list, # TBD
