### ISSUE TITLE
Infrastructure: Create sandbox Terraform env

### ISSUE THREAD

**Issue by SarahJaine** [HHS/Head-Start-TTADP#112]
In issue https://github.com/HHS/Head-Start-TTADP/issues/23, we created terraform envs for dev, staging and prod and applied the terraform state in dev. This instantiated the dev RDS instance. I held off on creating the sandbox env because I did not want to create infrastructure for which there was no immediate need. I also didn't want a tf state sitting unapplied. This ticket is only to be pulled into a sprint when the sandbox database is needed.

Acceptance criteria:
- [x] create tf env for sandbox
- [x] tf env should include RDS instance for sandbox and whatever other infrastructure exists in dev

**Comment by rahearn** [comment]
Definition of Done

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] No linting errors or warnings
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
