### ISSUE TITLE
Enable selection of existing Goals in the Activity Report 

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#117]
**User story:** 
As a TTA Specialist writing an Activity Report, I want to choose from grantee goals that were established as part of the grantee's TTA Plan or in another TTA Hub AR so that I can track how my work contributes to progress towards those goals.  

**Acceptance Criteria:**
- [ ] The user can select grantee goals that were imported from the smartsheet TTA Plans or from an AR that was completed in the TTA Hub. (Non-grantees are post-mvp)
- [ ] the user can select multiple goals at once
- [ ] the more recent (last created) goals display on top

Note: 
- [ ] Goals from Smartsheet Grantee TTA Plans are being imported if their status is "not started" or "in progress" 
- [ ] Goals in the smarthub will not have a status
- [ ] Goals from Smartsheet AR's are not being imported

**Link to design
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880470/simulate/sitemap

**SmartSheet forms showing current goal display:** 
- [TTA Plan](https://app.smartsheetgov.com/b/form/6ffe13b44db5492ab36a97e76a098941)

**Requirements and Considerations:**
- Goals in the Smartsheet are free text, so consider issues arising with pulling in free text
- Goals in the smart sheets can be short or very long, so consider issues arising with lengthier entries. Real example: "Grantee will receive support in developing a full enrollment action plan that covers the 12-month under-enrollment period.
Grantee will receive strategies for ensuring they can consistently meet enrollment requirement via their ERSEA policies and procedures. Grantee will receive strategies for ensuring their partnership with Skyline leads to sustainable enrollment."

**Exclusions:**
- suppression of new goals created in another Activity Report while that report is still pending approval #101 
- Backend pull of data from Plan into Smart Hub database will be handled via #57 and #119 
- parsing or processing data to make it display better. For this story, we will display data as is without trying to make it look better. TBD on whether we need to do more in a later story.
- updates to the Established Goals based on updates to the TTA Plan SmartSheet will not be handled by our system, per discussion with Patrice and Damon on Oct 28th.
 - display of ancillary data in the Grantee TTA Plan associated with the goal (statuses, timelines, topics, objectives ) #168

**Comment by pamlo412** [comment]
@kryswisnaskas - we groomed this story in your absence. Assigning to you to point with the others.

**Comment by pamlo412** [comment]
Questions copied from #214, which work was merged into this ticket:
> @pamlo412 A few questions and comments about the acceptance criteria
> 
> > goals with a status of complete or suspended don't display
> 
> We talked before about goals not having statuses in Smart Hub. To make this acceptance criteria clearer we need to clarify that the displayed goals are either not yet completed if coming from SmartSheet or not completed based on other criteria if originated in the Smart Hub.
> 
> > In the Goals and Objectives section of an Activity Report, the user can select goals entered in previous ARs for the grantee (or grantees) entered in this report
> 
> ARs can be associated with grants that in HSES have 3 statuses: "active", "inactive" and "in closeout". I am assuming the displayed goals are for ARs with grants that are active, right?
> If so, are we showing goals from all of the previous ARs?

@kryswisnaskas I updated the AC to address your first point. Your second point is a question we need input from @PatricePascual-ACF on. I added a draft AC about it for her consideration.

**Comment by PatricePascual-ACF** [comment]
@marriej On this: - [ ] Should include goals from grants marked "active" 
This is not quite right and it refers to the Goals in the SS TTA Plans. 
TTA Plan goals have a status. 
We are only exporting goals that are: 
-- Not Started
--In Progress
(There are also two other Goal statuses in the SS TTA Plans: "Completed" or "Ceased/Suspended." 
Any Goals with these statuses are not being exported into the Hub.)
