### ISSUE TITLE
Create frontend multi-select component

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#128]
**User Story**
As a TTA Smart Hub user, I want to be able to select multiple options for some form dropdowns, so I can accurately complete a report.

Some examples of fields that need multi-select, `Other Specialist(s) involved in this activity (optional)`, `Who was this activity for?` and `Choose all topics covered`.

**Acceptance Criteria**
 - [ ] The frontend has a multi-select component that ingrates with [https://react-hook-form.com/](https://react-hook-form.com/)
 - [ ] The multi-select component is styled like a USWDS dropdown
 - [ ] The multi-select component is accessible
 - [ ] Replace current Activity Report dropdowns that need to be multi-select with the new component
 - [ ] Enable type-ahead to help users find what they want to select

**Comment by rahearn** [comment]
Definition of Done

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] Code is meaningfully tested
- [x] No linting errors or warnings
- [x] UI meets WCAG 2.1 - Levels A and AA
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
