### ISSUE TITLE
Improve datepicker keyboard support

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#129]
**User Story**
As a TTA Smart Hub user, I want the date picker to work well with the keyboard, so I can navigate the site only using the keyboard.

**Context**
https://github.com/HHS/Head-Start-TTADP/pull/120/files/5d9976a05fa7b4c14c625c84603173e6df191f94#r513491898

**Acceptance Criteria**
 - [x] The date picker component can be used easily with keyboard input

**Comment by rahearn** [comment]
Definition of done:

- [ ] The business and/or user value of a story has been met
- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Code has deployed to a staging environment
- [ ] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [ ] OSCAL templates are completed when security controls are implemented or modified.
