### ISSUE TITLE
Review and submit a report for approval

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#135]
**User story:**
As a Regional TTA Specialist who has completed anActivity Report, I want to submit it for approval to my approving manager.

**Acceptance criteria:**
- [x] users can't submit until all required fields are completed  (See note in Comments, 11/17)
     - [x] if a user tries to submit before all required fields are completed, a validation error message displays 
- [x] user can use the menu to navigate through the report sections to review before clicking submit
     - [x] if all required fields are not completed, a validation error message displays
- [ ] the report's creator and any others assigned as collaborators (see #109) can select one manager to approve.
- [ ] the system prefilters the selectable managers to those users who have permissions to this region and one of the following roles: 
    - [ ] TTAC
    - [ ] Early Childhood Manager
     - [ ] Grantee Specialist Manager
- [ ] the report's status changes on submission to "Submitted for approval"
- [x] the author and all collaborators on a report can submit the report for approval
- [x] the report remains open for editing (author and collaborators only) on submission

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/133997819/simulate/no-panels

**Exclusions:**
- creation of roles - see #52 
- handling managers' requests for revisions, #138
- managers' approval workflow #137
- display of approvers and the status of their approvals #227 
- validating that a user doesn't select themselves as an approver - this scenario could only happen if one of the people in the above-listed approver roles was also the author or a collaborator. Confirmed with Product Owner that we can let users in these roles assign themselves as approvers. 
- undoing a wrongly assigned manager - handled by the manager rejecting - see #138
- Preview view of the report before submission - post MVP see [Jira 10](https://ocio-jira.acf.hhs.gov/browse/TTASH-10)

**Comment by PatricePascual-ACF** [comment]
Hi, @pamlo412. I don't think this is ready for grooming, unfortunately. 
Damon, Aricka and I need to review the list of required fields. We have not had that discussion (11/17).

**Comment by pamlo412** [comment]
Per discussion with @PatricePascual-ACF at grooming, we will handle the validations via a different story.

@kryswisnaskas - we need you and the devs to point this one.

**Comment by pamlo412** [comment]
@jasalisbury : In Product Planning today, we broached the possibility that we don't want to allow the user to enter multiple managers as approvers. @PatricePascual-ACF will be discussing this issue with Damon soon. I'm noting it here because this is the story with the multiple approvals requirement.
