### ISSUE TITLE
Manager Note for Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#138]
**User story:**
As a TTA manager reviewing an Activity Report, I want to be able to leave a comment at the end of the report.

**Acceptance criteria:**
- [x] The field is optional.
- [x] Notes from the specialist are viewable in this area above the manager note entry box.
- [x] Completed notes are labeled as "Manager Notes"
- [x] Field can handle a large amount of text
- [x] No formatting available. (ignore bold "Lou-Anne" in notes field in design)

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880478/simulate/sitemap

**Exclusions:**
- approval of the report, #137 
- display of revisions-requested report in the specialist's queue, #181 
- if the manager makes changes directly in the report, there is no indicator of what changed. Only the comments field is separated out to distinguish the manager's feedback
- we will handle editing of the report by the manager (here or later/elsewhere) via a separate story

**Comment by pamlo412** [comment]
Discussed at standup grooming: we want to complete design review with @PatricePascual-ACF before grooming this story. We may want multiple comment boxes (one per section) rather than one comment box over all.

**Comment by matt-dobson** [comment]
@PatricePascual-ACF This is one that might be able to be split by role type. With a story for the manager experience and a story for the specialist experience.
