### ISSUE TITLE
Activity Report navigation (stepper replacement)

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#140]
**User story:**
As a TTA specialist working on an activity report, I want to be able to enter sections of the report non-linearly so that I can complete the report one section at a time, as I have the information ready.

**Acceptance criteria:**
- [x] A section menu is added to the activity report
- [x] a status tag displays for each section (Not Started, In Progress, Complete)
- [x] The already-implemented fields are broken out into their appropriate sections/pages
- [x] the user can navigate to any section and complete fields in any order (aka the "anti-stepper")

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/133952430/comment/no-panels

**Exclusions:**
- full population of each section will be handled via #99, #100, #101,  and #135. This story is just to get the menu in place and the already-implemented fields moved.
- handling of browser navigation, # TBD

**Comment by rahearn** [comment]
Definition of Done

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [ ] Code is meaningfully tested
- [x] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [x] OSCAL templates are completed when security controls are implemented or modified.
