### ISSUE TITLE
Assigning report IDs to Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#145]
**User story:**
As a TTA specialist referencing my work in time reports and other contexts, I want activity reports to each have their own ID that I can reference so that I don't have to waste time naming or describing the report.

**Acceptance criteria:**
- [ ] the system generates and stores a report ID 
- [ ] the system can display the report ID in the UI in the format Region#-DocumentType-incrementing number assignment. SmartSheet IDs are: R09-AR-00000049, where AR = Activity Report. 
Hub IDs will display incrementally without the "000000"- example: R09-AR-213.
- [ ] each report ID is unique. To avoid duplicate IDs as following the transition from SmartSheet, Hub ID numbers for all regions will begin at a number greater than any region's current AR count. That safe ID number can be assumed to be "AR-1000." @PatricePascual-ACF will validate this number as we approach launch.  

**Dependencies:**
- saving the report #98 
- create the activity report

**Engineering notes:**
The ids are not independently incremented, a global increment should be used.

**Exclusions:**
- displaying the ID in the report and on the landing page, story TBD

**Comment by PatricePascual-ACF** [comment]
@pamlo412 I gave a value to the starting ID number above, and will revaldiate it before we move data over from SmartSheet.

**Comment by jasalisbury** [comment]
From https://gsa-tts.slack.com/archives/C017RJ4GEET/p1612903356126900

> New format is R0#-AR-1
