### ISSUE TITLE
Handle system behavior when user uses browser controls to navigate Smart Hub

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#152]
**User story:**
As a TTA specialist working in the Smart Hub, I want the Hub to respond appropriately when I click the navigation options in my browser, so that navigating using the browser's controls does not confuse me or result in unintended consequences.

**Acceptance criteria:**
- [x] if the browser's Back option is enabled and the user selects it, the Smart Hub navigates to the page/url last viewed by the user based on the browser's history of pages visited and that page displays in the same state in which the user last saw it
- [x] if the browser's Forward option is enabled and the user selects it, the Smart Hub navigates to the "next" page/url based on the sequence of pages in the browser's history of pages visited
- [x] if the user selects the browser's refresh option with unsaved entries on the screen, the system refreshes to the last saved entries.
- [x] if the user bookmarks or favorites a Smart Hub page, selecting that bookmark or favorite will route the user to that page directly after login
- [x] if the user selects the browser's close option, the session cookie is deleted and they are logged out.
- [x] Supports Chrome and IE11, Edge

**Exclusions:**
- handling of exceptions: we will handle exceptions in the story specific to that feature or capability. For example, when a user filters the list on the Home page and then clicks Back, we may want the Back option to take them to the last filtered view, rather than the last URL they visited.

**Comment by pamlo412** [comment]
@kryswisnaskas - here's the story you've asked for re handling browser nav controls.
