### ISSUE TITLE
Create a new report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#153]
**User story:**
As a regional TTA specialist or manager, I want a prominent (easy to spot) option to create a new activity report.

**Acceptance criteria:**
- [ ] A button is available to create a new activity report. See Design for its location and other specs.
- [ ] this button is hidden from users who do not have write permission to their region
- [ ] Each user can only have write access to one region.

**Link to design** 
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880467
empty state: https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880466

**Related:**
- generating an ID for the new report - #145 
- after report submission #266

**Comment by pamlo412** [comment]
This story is ready for team grooming.

**Comment by pamlo412** [comment]
@PatricePascual-ACF Please see the exclusion I just added to this story about the create-report button being allowed to display to all users, even those who don't need to create it. Is this ok?
