### ISSUE TITLE
Selecting Topics from a list filtered by role

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#161]
Changed this issue to be Predictive typing everywhere! - https://ocio-jira.acf.hhs.gov/browse/TTASH-31

**User Story:**

As a TTA Specialist completing an Activity Report, I want to be able to select topics from a predefined list of topics most relevant to me based on my role so that I can quickly select the most appropriate/likely options.

**Acceptance criteria:**
- [ ] when a user clicks in the Topics field, the options in the dropdown are filtered based on their role
     - [ ] Topics and assigned specialists are here: https://app.smartsheetgov.com/sheets/hR6H8jVwR8PhgMGGvcX8vWRfj7x9c62JMR3jWXc1?view=grid
     - [ ] note that topics may map to more than one role
- [ ] the user can select 1 to n topics for inclusion in the report (this AC may be covered by #235 if that story is done before this one)
- [ ] the user can deselect topics (this AC may be covered by #235 if that story is done before this one)

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/133952432/simulate/no-panels

**Exclusions:**
- ability to see the unfiltered list of all topics #235

**Comment by pamlo412** [comment]
@PatricePascual-ACF and @arickalewis1 - do we have documentation of the mappings between topics and user roles and regions? We need them for this story.

**Comment by pamlo412** [comment]
Thanks @PatricePascual-ACF - if I understand you correctly, even though we won't filter by region, we do still need this story for the MVP so as to filter by specialist (which I hope means by role). To do that, we'll need some rules for which topics to display and/or some kind of mapping table to look up which topics to display for which users. Those rules or mappings are what I'm looking for.

**Comment by pamlo412** [comment]
Ready for grooming with developers, except for answer to question about mapping of topics to roles.

**Comment by PatricePascual-ACF** [comment]
@lstraghalis - fyi - I tagged "needs research" but I mean way down the road.
