### ISSUE TITLE
Enter predefined Grantee program types 

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#170]
**User story:**
As a TTA Specialist completing an Activity Report, I want to select the Grantee program type so I can record who received TTA. 

**Acceptance criteria:**
- [ ] if the user selects Grantee, the Program Type field displays in the report
- [ ] there are three Program Type values: Head Start (ages 3-5); Early Head Start (ages 0-3); EHS-CCP. 
- [ ] the user can select one or more program types for each report (see design)
- [ ] if the user selects Non-Grantee, the Program Type field does not display

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880468

**Comment by pamlo412** [comment]
Discussed with @PatricePascual-ACF and Damon yesterday (and again with Patrice this morning).  This story is ready for team grooming.
