### ISSUE TITLE
Enable entry of grantee participants

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#172]
**User story:**
As a TTA Specialist completing an Activity Report, I want to be able to select the appropriate role names for the participants in the activity so that we have a record of the kinds of people we worked with on a given activity.

**Acceptance criteria:**
- [x] The label for the participants dropdown is updated to match the latest design
- [x] the options in the dropdown change based on whether the user selected either the Grantee or Non-Grantee radio button in the same section of the report. Users cannot select both for a single report.
     - [x] the options can be found in [the Region 14 Smartsheet]
**Grantee participant values**
CEO / CFO / Executive
Center Director / Site Director
Coach
Direct Service: Other
Family Service Worker / Case Manager
Fiscal Manager/Team
Governing Body / Tribal Council / Policy Council
Home Visitor
Manager / Coordinator / Specialist
Parent / Guardian
Program Director (HS / EHS)
Program Support / Administrative Assistant
Teacher / Infant-Toddler Caregiver
Volunteer

**Non-Grantee participant values** 
Local/State Agency(ies)
HSCO
OCC Regional Office
OHS Regional Office
Regional Head Start Association
Regional TTA Team / Specialists
State Early Learning System
State Head Start Association
Other  (Note: We do not have a separate data capture for what user means by "other" - this is intentional)

**Exclusions:**
-None

**Comment by pamlo412** [comment]
@PatricePascual-ACF - we need the options for the participants dropdown, both for Grantee participants and Non-Grantee participants. I also want to confirm in this story what we said in product planning--that it's fine that the user can't capture both grantee and non-grantee participants. See my mention of this point in the Exclusions.

**Comment by pamlo412** [comment]
Updated story with link to Smartsheet per Patrice's answer in Slack to my question above.

**Comment by PatricePascual-ACF** [comment]
@pamlo412 
> Updated story with link to Smartsheet per Patrice's answer in Slack to my question above.
I had already moved the values over so folks don't need to go to the AR in SS. Will try to get that done for all stories.
