### ISSUE TITLE
Display creator/collaborator's work list

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#181]
**User story:**
As a creator or collaborator of an AR, I want to see the Activity Reports that need my action so that I can keep track of what I need to do.

**Acceptance criteria:**
- [ ] users that can write reports will see:
     - [ ] the status of the reports is "draft" or "needs action"
     - [ ] the currently logged-in user is either the creator or tagged as a collaborator 

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880467

**Exclusions:**
- filtering reports lists #186
- - autocreation of shell reports that need to be completed (and/or notifications that a report is needed) - eventually, we anticipate wanting to do something like this, but in the MVP we won't really have enough data around planned activities (other than what's in the reports) to help specialists with this kind of proactive prompt.

Linked items:
- display of manager's work list #191 
- pagination of this list  #185  
- list of all reports #5

**Comment by pamlo412** [comment]
This story was reviewed in Prod Planning today and is ready for team grooming.

**Comment by matt-dobson** [comment]
@PatricePascual-ACF I think this is a candidate to be split by user role. The managers and specialists will use it in different ways. That should make it easier to associate this story with approval process stories too.

**Comment by pamlo412** [comment]
Agreed at pregrooming to split this story based on the rule of display for each user type.

**Comment by pamlo412** [comment]
Discussed this story at Product Planning today and agreed to break it into smaller stories based on user type. Created #191 and #192 as a result.

Not ready for team grooming yet: @PatricePascual-ACF needs to review them one more time.
