### ISSUE TITLE
Display manager's work list

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#191]
**User story:**
As an activity report approver, I want to see the work assigned to me in My Activity Report Alerts so that I can keep track of what I need to do and get it done on time.

**Acceptance criteria:**
- [ ] a list of reports assigned to the approver displays in My Activity Report Alerts on the post-login landing page
- [ ] assigned report status could be "needs action" or "draft" :
- [ ] the user has been entered in the report as an approver

**User roles that approve Activity Reports (see #135):**
     - TTAC
     - Early Childhood Manager
     - Grantee Specialist Manager

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880467

**Note**
Same design is used. Access by my assigned reports (reports I am the approving manager for).

**Exclusions:**
- display of specialist's work list #181 
- display of empty state of work list #192 
- approving ARs #137 
- pagination of this list  #185  
- list of all reports #5 
- filtering reports lists #186
