### ISSUE TITLE
Selecting goals from previous Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#214]
**User story:**
As a TTA specialist creating an activity report, I want to be able to select from a list of goals that were written in previous ARs for this grantee so that the TTA records accurately reflect all activities that addressed the same goals. 

**Acceptance Criteria:**
- [ ] In the Goals and Objectives section of an Activity Report, the user can select goals entered in previous ARs for the grantee (or grantees) entered in this report
- [ ] the more recent goals display on top
- [ ] goals with a status of complete or suspended don't display
- [ ] the source of the goal (TTA Plan or previous AR) displays

**Exclusions:**
- pulling goals from SmartSheet ARs into the Hub db #215 
- display of goals entered in SmartSheet TTA Plans #117 
- handling the anticipated increase in the length of this list over time (post MVP) #217

**Comment by kryswisnaskas** [comment]
@pamlo412 A few questions about the acceptance criteria

> goals with a status of complete or suspended don't display

We talked before about goals not having status in Smart Hub. Has this changed? Or is it referred to a set of objectives statuses?

> In the Goals and Objectives section of an Activity Report, the user can select goals entered in previous ARs for the grantee (or grantees) entered in this report

ARs can be associated with grants that in HSES have 3 statuses: "active", "inactive" and "in closeout". I am assuming the displayed goals are for ARs with grants that are active, right?
If so, are we showing goals from all of the previous ARs?

**Comment by pamlo412** [comment]
Closing this story as we decided at grooming we could do this work in #117 . Tagging @kryswisnaskas to inform her.

**Comment by pamlo412** [comment]
@kryswisnaskas Since we merged this ticket with #117, I have moved your question to that issue and answered it there.
