### ISSUE TITLE
Enable entry of context about an activity

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#218]
**User story:**
As a TTA specialist creating an activity report, I want to be able to enter context notes to an activity so that I can elaborate on any reasons for, or aspects of, the activity that aren't already clear from other information entered in the report. Also allows regions to "customize" their reports as needed.

**Acceptance Criteria:**
- [x] A free text box is available in the Goals and Objectives section
- [x] there is no character limit
- [x] Text entry is optional.
- [x] "Context" is associated with the Activity not individual goals.

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880470

**Exclusions:**
- WYSIWYG editor #222
