### ISSUE TITLE
Specialist addresses manager's revision requests and resubmits AR

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#225]
**User story:**
As a specialist opening a report marked as "Needs Action" I want to see the manager's notes upon opening.

**Acceptance criteria:**
- [ ] On opening a report that Needs Action, the default focus is the bottom of the report where the manager's notes display
- [ ] the manager's notes are view-only
     - [ ] reminder: per #135, the rest of the submitted report is editable 
- [ ] the author/collaborator can navigate through the report and make edits
- [ ] any author/collaborator can resubmit the report 

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880477/simulate/sitemap

**Exclusions:**
- manager's request for revisions #138
