### ISSUE TITLE
Selecting topics from the unfiltered list of all topics

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#235]
**User story:**
As a TTA Specialist completing an Activity Report, I want to be able to select topics from the entire list of available topics so that I can include in my report all of the topics we covered.

**Acceptance criteria:**
- [x] when a user clicks in the Topics field, the user also has an option to search the entire list of predefined topics
- [x] the user can select 1 to n topics for inclusion in the report 
- [x] the user can deselect topics 

**Topic list** (1.6.21)
Behavioral / Mental Health
Child Assessment, Development, Screening
CLASS: Classroom Management
CLASS: Emotional Support
CLASS: Instructional Support
Coaching
Communication
Community and Self-Assessment
Culture & Language
Curriculum (Early Childhood or Parenting)
Data and Evaluation
ERSEA
Environmental Health and Safety
Facilities
Family Support Services
Fiscal / Budget
Five-Year Grant
Human Resources
Leadership / Governance
Learning Environments
Nutrition
Oral Health
Parent and Family Engagement
Partnerships and Community Engagement
Physical Health and Screenings
Pregnancy Services / Expectant Families
Program Planning and Services
QIP
Recordkeeping and Reporting
Safety Practices
Teaching Practices / Teacher-Child Interactions
Technology and Information Systems
Transition Practices
Transportation
Other  (@jasalisbury - in case you're wondering, this does not have/need a corresponding open-text field)

**Design:**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/133952432/simulate/no-panels

**Exclusions:**
- filtering the list of topics by role: #161 (post-MVP)
