### ISSUE TITLE
Setup New Relic Account

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#26]
We need a monitoring solution so we know the health of the system. New Relic seems the obvious choice:

 1. It is hosted, so we will not have to worry about setting up or maintaining any servers
 2. It integrates easily with [node/express](https://newrelic.com/nodejs/express)
 3. It is already [FedRAMP Authorized](https://newrelic.com/press-release/20200304) for moderate impact

Only downside to using New Relic I can think of would be pricing, which is hard to know at this point. Looks like we can have a New Relic sells rep get in [contact with us](https://newrelic.com/contact-sales?ref=publicsector).

See the New Relic [public sector page](https://newrelic.com/solutions/industry/public-sector).

## Definition of Done

 - [x] Decision on usage of New Relic is made

If New Relic is used:

 - [x] New Relic account with any API keys needed by the backend created
 - [x] The backend is setup to send monitoring information to New Relic

**Comment by jasalisbury** [comment]
@rahearn do you want to take point on setting up a meeting to talk with a sales rep?

**Comment by rahearn** [comment]
Yes, I'll take that on.

**Comment by pamlo412** [comment]
Moved from Sprint 0 backlog to Grooming backlog. This one isn't ready for dev yet.

**Comment by rahearn** [comment]
Update: I sent a request to the sales team to get more information on pricing.

**Comment by pamlo412** [comment]
Agreed at planning discussion today that ideally OHS should own this monitoring tool, so we will leave this ball in 18F's court until mid November. If @rahearn still hasn't resolved the issue with licenses by then, we will explore having Ad Hoc purchase a license and own the tool. We need this monitoring tool to be up and running 3 or 4 sprints before go live (ideally).

**Comment by rahearn** [comment]
Update:

1) I am signing up for a free-tier account to use for dev and staging
2) New Relic setting up another call to talk about enterprise licensing
