### ISSUE TITLE
Prevent editing of reports not in "Draft" or "Needs Action" mode

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#285]
As a specialist, I want my reports to not be editable after submitting for approval, so I can be sure of what the manager is approving

---

Once a report has been submitted we do not want that report to be editable (except for the `managerNotes` and the `status` field). This will ensure we don't get into a strange situation where a manager approves an incomplete report.

For more context https://gsa-tts.slack.com/archives/C017RJ4GEET/p1612543608107300

**Acceptance Criteria:**
- [ ] Report fields are only editable by authors when the report is in "Draft" or "Needs Action" status. `managerNotes` and `status` can still be updated by the manager once the report has been submitted
- [ ] Any automatic report updating/saving is only enabled when the report has a status of "Draft" or "Needs Action"
- [ ] For submitted reports the review page for authors is updated to allow authors to revoke the submission moving the report back to "Draft"
