### ISSUE TITLE
Form navigation update

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#313]
As a Smart Hub user, I want form navigation to be consistent, so I don't have to think about how I want to navigate the form

---

Navigating the form via the `side nav` or `Continue` button behave differently. Clicking `Continue` validates the form and doesn't allow the user to move to the next page until the form is valid. The `side nav` always allows the user to change the page even if the form is invalid. We want these two forms of navigation to behave the same.

**Additional Context**
https://gsa-tts.slack.com/archives/C017RJ4GEET/p1614007348000500

**Acceptance Criteria**

- [ ] Clicking `Continue` moves the user to the next page regardless of the validity of the form
- [ ] When the user navigates (`Continue` or `side nav`) the current page is marked as complete if the form is valid
- [ ] A draft is saved to the API when navigating
- [ ] Error messages are shown on page load after the user visits the review page and navigates to a different page
