### ISSUE TITLE
Implement accessibility scanner on CI/CD pipeline

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#41]
implement accessibility scan (ad hoc's choice, though document why you made your choice)

**Comment by pamlo412** [comment]
We met on axe-core as the tool we expect to use. Need to discuss again before grooming and pointing this story.

**Comment by pamlo412** [comment]
Per discussion at planning, we can let this one slip to Sprint 2 and still submit user-facing stories in Sprint 1. That said, it is a high priority to get this one done asap.

**Comment by SarahJaine** [comment]
@rahearn Are there some requirements (or any more details) around how the accessibility checks are supposed to be implemented? This ticket uses the word "scan" because we assumed this would run like OWASP zap against a local server instance spun up on the CI pipeline. Was that a requirement? It looks like axe-core can be used to write functional tests- which might be easier to write and quicker to run.

**Comment by rahearn** [comment]
> Are there some requirements (or any more details) around how the accessibility checks are supposed to be implemented?

the only requirement is that there is something to catch accessibility issues running in CI/CD. I like a scan, because then developers don't need to remember to write the tests themselves, but I’m open to hearing about the benefits of writing those tests and if the team thinks that writing them is a worthwhile cost to take on

**Comment by rahearn** [comment]
Definition of Done checklist:

- [ ] The business and/or user value of a story has been met
- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Code has deployed to a staging environment
- [ ] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [ ] OSCAL templates are completed when security controls are implemented or modified.
