### ISSUE TITLE
Display list of Activity Reports

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#5]
**User story:**
As a user, I want to see a list of Activity Reports upon login.

**Acceptance Criteria:**
- [ ] A list of Activity Reports is filtered to display all reports to which the current user has access
- [ ] the default sorting of the list is by the Last Saved date, starting with the most recent
- [ ] the columns in the list are as indicated in the design

**Link to design**
https://preview.uxpin.com/ad995fd722bd26c0f9a1c8a115f1b41833637308#/pages/134880467

**Authorization Rules**

Users can view reports that are:

1) created by user, with any status
1) where user is in collaborators, with any status
1) Approved reports in regions that user has READ_APPROVED_REPORTS permission
1) All reports in regions that user has READ_ALL_REPORTS permission

**Accompanying:**
- exporting/printing reports - see #108
- generating a new report - see #153  
- a list of current user's work - see #181 
- additional sorting #187
- Region Selector story @marriej 
- Pagination story https://github.com/HHS/Head-Start-TTADP/issues/273

**Post-MVP:**
- filtering the list - see #186 
- pagination of the list - see #185

**Comment by rahearn** [comment]
Role based authorization will be needed from the start, though I agree that those can be implemented in separate stories.

**Comment by pamlo412** [comment]
Ready for grooming with the team.
