### ISSUE TITLE
Backend story: implement database schema and API endpoints for admin tool

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#50]
**User story:** As an admin for the TTA Smart Hub, I want to be able to retrieve and save the user data from/to the Smart Hub backend, so that user permissions can be created or updated. 

**Acceptance Criteria:**

1. Create database schema
2. Implement API endpoints such that the Smart Hub can save user information for use in managing permissions to the Smart Hub.  

**Implementation notes:** 
- need user endpoint: email address, full name, region, job title
- need methods: get, put, delete
- need database migrations to change the schema
- per discussion of #51, we will generally implement permissions as needed for each new feature. For this initial work, we'll implement the following permissions:
          - ADMIN - Can edit users with the admin UI
          - APPROVE_REPORTS
          - READ_REPORTS - Can view activity reports for the region
          - READ_WRITE_REPORTS - Can view and update/create activity reports for the region
- we'd like a Region 14 (a fake region) so that we can use it for usability and other testing. The value of it is that it allows anonymous data and prevents our users from thinking about region-specific issues when we don't want them to be thinking that way

**Exclusions:** 

- updates to prototype UI based on what we learn in this story see 
- getting the HSES users into our database (check to see if we already have a story)

**Team notes:**
- we will need to come to a consensus on how we want permissions to work. Josh suggests separating each capability from the regions and having permissions be the combination of a region and capability. An example of a permission would be READ_REPORTS (the capability) on region 1. Some capabilities would be "regionless" (like the ADMIN capability). The admin UI as currently built assumes this is the path we will take but it could easily be changed.
- we will be the source of truth for who has Smart Hub logins but we leave HSES login management to HSES. Patrice and Ryan will look into how HSES is managing this so we understand better any risks that we may be inheriting/extending.

**Comment by rahearn** [comment]
> Josh suggests separating each capability from the regions and having permissions be the combination of a region and capability

I'm very much in favor of this approach, along with the further clarification you mention of the capabilities being related to Smart Hub features and not job titles.

**Comment by rahearn** [comment]
Definition of Done

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] Code is meaningfully tested
- [x] No linting errors or warnings
- [x] UI meets WCAG 2.1 - Levels A and AA
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
- [x] Logical Data Model Diagram is updated on DB schema changes.
- [x] Public API methods are documented when added or changed.
