### ISSUE TITLE
Pull goals & related data entered in Grantee TTA Plan SmartSheets into the Smart Hub database

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#57]
**User story:** 
As a Smart Hub developer, I want the goals and related data captured in the TTA Plan SmartSheet to be available in the Smart Hub database for display and selection in the Smart Hub Activity Report so that I don't have to make a real-time call to SmartSheets everytime a Smart Hub user wants to associate an Activity Report with a Goal established in the Plan. 

**Acceptance Criteria:**
Interfacing with the anonymized SmartSheet Plan (created by @rahearn and based on actual Region 5 plans, pull the following data into the Smart Hub database:
      - **goal**
            - each goal must be associated with a unique grantee/grant number:
            - each goal should be identifiable in the DB as coming from the SmartSheet TTA Plan. (This attribution is wanted because we will also have goals pulled from other Activity Reports, both SmartSheet ARs and Smart Hub ARs, as well as free text goals entered for the first time in an Activity Report.)
      - **status**
           - this is the status of the goal as entered in the Plan. Note that in our ARs, it's the objectives that will have statuses, not the goals. But we want to pull in the Plan goal's status via this story so as to use the status to decide whether to display a Plan Goal to the AR user or not. For example, if the Plan Goal's status is "closed" or "ceased/suspended", we won't display it to the end user.
       - **topics**
             - capture and store the topics associated with each goal in the Plan. Store them so that we know which topics go with which goals
         - **timeframe**
             - capture and store the timeframe (a number indicating months) associated with each goal in the Plan. Store them so that we know to which goal each timeframe pertains.
          
     
**SmartSheet forms showing current goal display:** 
- [TTA Plan](https://app.smartsheetgov.com/b/form/6ffe13b44db5492ab36a97e76a098941)

**Requirements and Considerations:**
- Goals in the smart sheet are free text, so consider issues arising with pulling in free text
- Goals in the smart sheets can be short or very long, so consider issues arising with lengthier entries. Real example: "Grantee will receive support in developing a full enrollment action plan that covers the 12-month under-enrollment period.
Grantee will receive strategies for ensuring they can consistently meet enrollment requirement via their ERSEA policies and procedures. Grantee will receive strategies for ensuring their partnership with Skyline leads to sustainable enrollment."
- Goals in the Grantee TTA Plan have statuses: consider whether we can show or hide them in the Activity Report based on a given status in the plan.
- Goals in the Activity Report to not have statuses: But the _Objectives_ have status. (Objectives will be a different story.) 
(Not sure the following are for this story?)

**Exclusions:**
- Front end UI and UX will be handled by #117 
- one-time pull of this goal information from production Smartsheet Plans into the Smart Hub db #119 
     - post go-live updates to the Established Goals based on updates to the TTA Plan SmartSheet will not be handled by the system, per discussion with Damon and Patrice on Oct 28th.
- pulling goals from SmartSheet Activity Reports into the Established Goals field will be handled via #37 
- aligning Objectives with goals will not be handled in the MVP
- parsing or processing data to make it display better. For this story, we will capture and store the data as is. TBD on whether we need to do more in a later story.
- handling of goal IDs: some regions assign an ID to each goal for ease of tracking and reference but there isn't consistency on this point yet and it's not a discrete field in the Smartsheet. We will create IDs for goals created in the Smart Hub. See #151 (which has been descoped from the MVP)

**Comment by rahearn** [comment]
Definition of Done:

- [ ] The business and/or user value of a story has been met
- [ ] CI pipeline green
- [ ] Code is meaningfully tested
- [ ] No linting errors or warnings
- [ ] UI meets WCAG 2.1 - Levels A and AA
- [ ] Code has deployed to a staging environment
- [ ] Security scans have passed
- [ ] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [ ] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [ ] Logical Data Model Diagram is updated on DB schema changes.
- [ ] Public API methods are documented when added or changed.
- [ ] OSCAL templates are completed when security controls are implemented or modified.
