### ISSUE TITLE
Stop using memory session store for `express-session`

### ISSUE THREAD

**Issue by jasalisbury** [HHS/Head-Start-TTADP#73]
We use [express session](https://www.npmjs.com/package/express-session) to manage user sessions. The default session store is the memory session store. This store is not appropriate for production and will leak memory. We need to figure out which session store we should use for our deployed environments.

This story could easily be split into two, one being a Spike to determine which session store to use and a second to implement the decision made in the spike.

**Acceptance Criteria**

 - [ ] A new session store is picked from [this list](https://www.npmjs.com/package/express-session#compatible-session-stores) Note: session store needs to be created via terraform as a cloud foundry/cloud.gov artifact, so we're probably limited to redis or rds postgres
 - [ ] Any new infrastructure that is needed is added to terraform
 - [ ] The backend uses the new session store

**Comment by rahearn** [comment]
@kryswisnaskas I looked over https://github.com/expressjs/cookie-session and I'm in favor of using it for session storage. We should be sure to keep any sensitive data out of the session, but I think that's a good best practice to follow anyway.
