### ISSUE TITLE
As a user who has left my computer, I should be logged out after a period of inactivity, so my account remains secure (AC-2(5), AC-12)

### ISSUE THREAD

**Issue by rahearn** [HHS/Head-Start-TTADP#79]
**User story:**
As a user who has left my computer for 25 minutes or longer, I want the system to log me out of Smart Hub so the site remains secure.

**Acceptance Criteria:**
1. After 25 minutes of inactivity, the user is given a warning and option to continue session.
2. If the user clicks anywhere on the screen, the message is dismissed and the session is restarted.
3. If the user doesn't click anywhere on the screen, then at the 30 minute mark, the system logs the user out of Smart Hub and redirects them to the Welcome page.
4. The length of the inactivity timeout is easily configurable (a config file is fine).

**Considerations:**
-  HSES's timeout will not affect our users. 

**Exclusions:**
- design by Aricka - she'll review what the developers build and if we need changes, they'll go into another story.
- autosaving of work before timeout - #98 
- locking of screen (rather than logout) - not needed

**Comment by rahearn** [comment]
Seems like there's supposed to be a *15* minute session lock, and a *30* minute session termination timeout. Asking for clarity from IPT on the practical differences between lock and termination for a web app.

**Comment by rahearn** [comment]
We can ignore the 15 minute session lock and only implement the 30 minute session termination

**Comment by pamlo412** [comment]
Added screen lock to list of exclusions. Assigned 8 points based on discussion with @kryswisnaskas and @jasalisbury

**Comment by rahearn** [comment]
Definition of done:

- [x] The business and/or user value of a story has been met
- [x] CI pipeline green
- [x] Code is meaningfully tested
- [x] No linting errors or warnings
- [x] UI meets WCAG 2.1 - Levels A and AA
- [x] Code has deployed to a staging environment
- [x] Security scans have passed
- [x] [Architectural Decision Records](https://adr.github.io/) are written for major infrastructure decisions with [the Nygard template](https://github.com/joelparkerhenderson/architecture_decision_record/blob/master/adr_template_by_michael_nygard.md).
- [x] Boundary and Data Flow Diagrams are updated when a change invalidates the current version.
- [x] Logical Data Model Diagram is updated on DB schema changes.
- [x] Public API methods are documented when added or changed.

**Comment by pamlo412** [comment]
Screen shot of timeout warning:
![image](https://user-images.githubusercontent.com/59671463/101673016-98b27d00-3a24-11eb-8847-cd44bd65009b.png)
