### ISSUE TITLE
Dev chore/task: Pull data from our database to populate fields implemented in UI before database was ready

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#90]
**Task description:**
This chore/task will replace UI-coded values with values pulled from our database. This work is needed for fields implemented before #23 was done.

**Acceptance criteria:**
The following fields pull the correct values from the database instead of fake values in the UI:
- [ ] ~Grantee Name~ handled via #163
- [ ] ~Grant ID~ also handled via #163
- [ ] ~Non-Grantee Name~ handled via #164 
- [ ] ~TTA Smart Hub users (for the collaborator field) - note that work to implement this field may include filtering and may warrant a separate story~ #109
- [ ] ~Reason~ #171
- [ ] ~Topics~ #161
- [ ] ~Participants involved in grantee activities~ #172
- [ ] ~Participants involved in non-grantee activities (different than the preceding list)~ #172

**Comment by pamlo412** [comment]
Closing this story as no longer needed because other stories are covering this need. See links to the other stories above.
