### ISSUE TITLE
Saving an Activity Report

### ISSUE THREAD

**Issue by pamlo412** [HHS/Head-Start-TTADP#98]
**User story:**
As a Regional TTA Specialist drafting a report on one of my TTA Activities, I want to be able to save my work in progress, without having to submit it for approval, so that I can draft reports on my various activities with grantees piecemeal when I have windows of time. 

**Acceptance Criteria:**
**Backend**
- [x] the activity reports table(s) is/are created
- [x] the API endpoint and documentation is available for the front end to save (GET, POST, PUT)
- [x] users can't save until they at least enter the grantee name 
- [x] the system captures the author and a datetime stamp on saving (so that we can display "last modified by" (name) and "last modified" (date))

**Frontend**
- [x] the system autosaves to the server every 2 minutes 
- [x] a message displays to users when an autosave or manual save happens:
     - [x] Message content: This report...[wording in design]
- [x] on reopening a saved report, users can edit the fields and re-save the report

**Exclusions:**
- document upload API endpoint https://github.com/HHS/Head-Start-TTADP/issues/150
- submitting the report for review/approval - #135
- collaborating with other specialists - #109 
- display of saved report on Home page - #181 
- local saving in the case of Internet connection going down - post MVP
- ability to draft and save offline and pull it into Smart Hub when you're back online - post MVP #144 
- assignment of report ID - #145

**Comment by SarahJaine** [comment]
Assigning this ticket to myself for Backend work only

**Comment by SarahJaine** [comment]
Per conversation in planning today, I'm excluding all cols that are displayed as multiselect FE components from this ticket:
- targetPopulation https://github.com/HHS/Head-Start-TTADP/issues/173
- headStartProgramType https://github.com/HHS/Head-Start-TTADP/issues/170
- granteeParticipantRole and otherParticipantRole https://github.com/HHS/Head-Start-TTADP/issues/172
- reason (example: 'Change in Scope',)
- topic (example: 'Behavioral / Mental Health',)
